services:
  - type: web
    name: telegram-test-bot
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DEBUG
        value: false
      - key: TEST_MODE
        value: true
      - key: TIMEZONE
        value: Asia/Dhaka
